export const CONGO_CITIES = [
  { label: 'Brazzaville', value: 'Brazzaville' },
  { label: 'Pointe-Noire', value: 'Pointe-Noire' },
  { label: 'Dolisie', value: 'Dolisie' },
  { label: 'Nkayi', value: 'Nkayi' },
  { label: 'Owando', value: 'Owando' },
  { label: 'Ouesso', value: 'Ouesso' },
  { label: 'Madingou', value: 'Madingou' },
  { label: 'Sibiti', value: 'Sibiti' },
  { label: 'Impfondo', value: 'Impfondo' },
  { label: 'Kinkala', value: 'Kinkala' },
  { label: 'Djambala', value: 'Djambala' },
  { label: 'Ewo', value: 'Ewo' },
  { label: 'Gamboma', value: 'Gamboma' },
  { label: 'Mossendjo', value: 'Mossendjo' },
  { label: 'Loudima', value: 'Loudima' },
  { label: 'Oyo', value: 'Oyo' },
  { label: 'Makoua', value: 'Makoua' },
  { label: 'Boundji', value: 'Boundji' },
  { label: 'Moungoundou Sud', value: 'Moungoundou Sud' },
  { label: 'Etoumbi', value: 'Etoumbi' },
];
